# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neh < Formula
  desc "neh is a sleek CLI application designed for high-speed, real-time
interaction with AI specializing in Large Language Models."
  homepage "https://github.com/neh-cli/neh"
  version "0.0.36"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neh-cli/neh/releases/download/v0.0.36/neh_Darwin_x86_64.tar.gz"
      sha256 "c8eae056f9617d67f06c1ea50d82f8c6671f1a37130ecdab35996742242bbffd"

      def install
        bin.install "neh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neh-cli/neh/releases/download/v0.0.36/neh_Darwin_arm64.tar.gz"
      sha256 "3dedb8c5ada0b79750f3c61031df180cf244d06d173e40b149839410509b8786"

      def install
        bin.install "neh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neh-cli/neh/releases/download/v0.0.36/neh_Linux_x86_64.tar.gz"
      sha256 "7d186859d5bb87e71cb24fbc42392884880386c2c06025811659e222f27cafe2"
      def install
        bin.install "neh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neh-cli/neh/releases/download/v0.0.36/neh_Linux_arm64.tar.gz"
      sha256 "42adc88a59d44117b02f0b5933555e090d67d40a24012cd8074d3ea06d29a120"
      def install
        bin.install "neh"
      end
    end
  end

  def caveats
    <<~EOS
      For zsh users:
      To avoid "no matches found" errors with special characters (?, *, etc.),
      add the following alias to your ~/.zshrc:

        alias neh='noglob neh'

      Then reload your shell configuration:
        source ~/.zshrc
    EOS
  end

  test do
    system "#{bin}/neh version"
  end
end
