# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neh < Formula
  desc "neh is a sleek CLI application designed for high-speed, real-time
interaction with AI specializing in Large Language Models."
  homepage "https://github.com/neh-cli/neh"
  version "0.0.33"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neh-cli/neh/releases/download/v0.0.33/neh_Darwin_x86_64.tar.gz"
      sha256 "41489862d3bb989af5ecf7047d92ec6324b84ee6a8e8a50beec777d055a0437e"

      def install
        bin.install "neh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neh-cli/neh/releases/download/v0.0.33/neh_Darwin_arm64.tar.gz"
      sha256 "2217870df1f8711fb039bd28ec0eaa397707ad048d3151a84abdab73f410a395"

      def install
        bin.install "neh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neh-cli/neh/releases/download/v0.0.33/neh_Linux_x86_64.tar.gz"
      sha256 "0b828c7d44638fb1bb09f1c4b8f5ce4a908653f49dce8fb68d54a5f5fba982cd"
      def install
        bin.install "neh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neh-cli/neh/releases/download/v0.0.33/neh_Linux_arm64.tar.gz"
      sha256 "ec918be062d157117222655c611a8fb3cac7b539495cb16478ae2bc4ffeefe37"
      def install
        bin.install "neh"
      end
    end
  end

  def caveats
    <<~EOS
      For zsh users:
      To avoid "no matches found" errors with special characters (?, *, etc.),
      add the following alias to your ~/.zshrc:

        alias neh='noglob neh'

      Then reload your shell configuration:
        source ~/.zshrc
    EOS
  end

  test do
    system "#{bin}/neh version"
  end
end
